apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc