# Default values for test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: hyperledger
replicaCount: 1

image:
  repository: hyperledger/fabric-ca
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.4.9"

container:
  command: ["/bin/sh"]
  args: ["-c", "fabric-ca-server start -b admin:Loxnetwork@123"]

environment: 
  - name: FABRIC_CA_HOME
    value: /etc/hyperledger/fabric-ca-server
  - name: FABRIC_CA_SERVER_TLS_ENABLED
    value: "true"
  - name: FABRIC_CA_SERVER_CA_NAME
    value: admin-ca
  - name: FABRIC_CA_SERVER_DB_TYPE
    value: postgres
  - name: FABRIC_CA_SERVER_DB_DATASOURCE 
    value: host=ca-postgres-svc port=5432 user=loxnetwork password=Loxnetwork@123 dbname=admin_ca sslmode=disable
  - name: FABRIC_CA_SERVER_CSR_HOSTS
    value: admin-ca-svc, admin-ca-svc.hyperledger.svc.cluster.local, localhost

pvc:
  name: common-pvc
  storage: 5Gi

volume:
  name: admin-ca-storage
  claimName: common-pvc

service:
  type: ClusterIP
  port: 7054
      
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}