# Default values for test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: hyperledger
replicaCount: 1

name: orderer-ca
type: blockchain

image:
  repository: hyperledger/fabric-ca
  pullPolicy: IfNotPresent
  tag: "1.4.9"

container:
  command: ["/bin/sh"]
  args: 
    username: admin
    password: Loxnetwork@123

service:
  type: ClusterIP
  port: 7054

