apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
  namespace: {{ .Values.namespace }}
  labels: 
    app: {{ .Values.name }}
    type: {{ .Values.type }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.name }}
    type: {{ .Values.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.name }}