apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
  namespace: {{ .Values.namespace }}
  labels: 
    app: {{ .Values.name }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{ .Values.name }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.port }}