apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: common-pvc
  namespace: hyperledger
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc