apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.pvc.name}}
  namespace: {{.Values.namespace}}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.pvc.storage}}
  storageClassName: efs-sc